## Data source
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie-booking
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:      ddl-auto: validate
  jackson:
    serialization:      fail-on-empty-beans: false
  flyway:
    url: jdbc:postgresql://localhost:5432/movie-booking
    user: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
springdoc:
  api-docs:    enabled: true
  swagger-ui:
    url: /swagger-ui.html
  packages-to-scan:  - cybersoft.javabackend.moviebookingjava14group4