## Data source
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie-booking
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:      ddl-auto: validate
  jackson:
    serialization:      fail-on-empty-beans: false
  flyway:
    enabled: true
    driver-class-name: org.postgresql.Driver
springdoc:
  api-docs:
    enabled: true
    path: /openapi/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan:  - cybersoft.javabackend.moviebookingjava14group4